### ISSUE TITLE
[Tracking Issue] HIR

### ISSUE THREAD

**Issue by Boshen** [Boshen/oxc#315]
HIR - High-Level Intermediate Representation

The goal of the HIR is to make a break through for the following RFCs

* https://github.com/Boshen/oxc/discussions/273
* https://github.com/Boshen/oxc/discussions/222
* https://github.com/Boshen/oxc/discussions/153
* https://github.com/Boshen/oxc/discussions/147

- [x] https://github.com/Boshen/oxc/pull/314
- [x] https://github.com/Boshen/oxc/pull/316
- [x] https://github.com/Boshen/oxc/pull/318
- [x] https://github.com/Boshen/oxc/pull/327
- [x] From top to bottom, lower the AST manually and "trim" out the parts we don't want. TypeScript definition should be the first layer to trim out.
- [x] https://github.com/Boshen/oxc/pull/335

Goal: Make mangler work again
- [ ] During this process I'll add a HIR Id to each node for future back references
- [ ] Modify the HIR so it includes scopes and symbols
  - [x] https://github.com/Boshen/oxc/pull/344 
- [ ] At this stage @YangchenYe323 should be able to start constructing the CFG directly within this lowering process
- [ ] Start desugaring syntax such as JSX and many more
- [ ] Semantic builder abstraction
----

I have no idea what I am doing but I'll boast this as ground breaking work for future javascript tools.
Compiler SDK can be achieved with this where semantic information can be queried through Node IDs. At this point I'll say we are ready for plugins.

The idea for compiler SDK comes from:

[roslyn-sdk](https://learn.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/)
[cargo metadata](https://doc.rust-lang.org/cargo/reference/external-tools.html)

I will document my progress in this issue, subscribe if you are interested.

**Comment by Boshen** [comment]
Everything is in place now, just need to keep working on the minifier, and this will reach feature complete 😄
